modded class PlayerBase
{
 	override void SetActions() 
	{
		super.SetActions();
	
		AddAction(ActionCheckSCGarbage_Bin);
		AddAction(ActionCheckSCGarbage_Container);
		AddAction(ActionCheckSCGarbage_Container_Glass);
		AddAction(ActionCheckSCGarbage_Container_Paper);
		AddAction(ActionCheckSCoffice_table_a);
		AddAction(ActionCheckSCMisc_PostBox2);
		AddAction(ActionCheckSCshelfs_small_crushed);
		AddAction(ActionCheckSCtable_crushed);
		AddAction(ActionCheckSCbed_large_metal_crushed);
		AddAction(ActionCheckSCclassroom_case_a_crushed);
		AddAction(ActionCheckSCclassroom_case_b_crushed);
		AddAction(ActionCheckSCclassroom_case_a);
		AddAction(ActionCheckSCclass_case_b_closed);
		AddAction(ActionCheckSCcase_sink_a);
		AddAction(ActionCheckSCmetalcase_01);
		AddAction(ActionCheckSCwardrobe_b);
		AddAction(ActionCheckSCwardrobe_a);
		AddAction(ActionCheckSCAmmoBox);
		AddAction(ActionCheckSCGarbage_Pile8);
		AddAction(ActionCheckSCGarbage_Pile7);
		AddAction(ActionCheckSCGarbage_Pile6);
		AddAction(ActionCheckSCGarbage_Pile5);
		AddAction(ActionCheckSCGarbage_Pile4);
		AddAction(ActionCheckSCGarbage_Pile3);
		AddAction(ActionCheckSCGarbage_Pile2);
		AddAction(ActionCheckSCGarbage_Pile1);
		AddAction(ActionCheckSCkitchen_unit_a_dz);
		AddAction(ActionCheckSCbag_dz);
		AddAction(ActionCheckSCoffice_desk);
		AddAction(ActionCheckSCvaulting_box_large);
		AddAction(ActionCheckSClab_teacher_bench);
		AddAction(ActionCheckSCkitchenstove_elec);
		AddAction(ActionCheckSCfridge);
		AddAction(ActionCheckSCwashing_machine);
		AddAction(ActionCheckSCvending_machine);
		AddAction(ActionCheckSCpokladna);
		AddAction(ActionCheckSClekarnicka);
		AddAction(ActionCheckSCskrin_bar);
		AddAction(ActionCheckSClibrary_a_open);
		AddAction(ActionCheckSClibrary_a);
		AddAction(ActionCheckSCcase_cans_b);
		AddAction(ActionCheckSCcase_bedroom_b);
		AddAction(ActionCheckSCcase_bedroom_a);
		AddAction(ActionCheckSCcase_a);
		AddAction(ActionCheckSCalmara);
		AddAction(ActionCheckSClocker_closed_v3);
		AddAction(ActionCheckSClocker_closed_v2);
		AddAction(ActionCheckSClocker_closed_v1);
		AddAction(ActionCheckSClocker_closed_blue_v3);
		AddAction(ActionCheckSClocker_closed_blue_v2);
		AddAction(ActionCheckSClocker_closed_blue_v1);
		AddAction(ActionCheckSCcashier);
		AddAction(ActionCheckSCtable_drawer);
		AddAction(ActionCheckSCWoodenCrate);
		AddAction(ActionCheckSCMisc_PostBox1);
		AddAction(ActionCheckSCbox_c_multi);
		AddAction(ActionCheckSCGarbage_Bin2);
		AddAction(ActionCheckSCGarbage_Container2_Open);
		AddAction(ActionCheckSCGarbage_Container2_Closed);
		AddAction(ActionCheckSCGarbage_Container_Plastic);
	} 
}